# Generated by Django 4.0.4 on 2022-06-14 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categorias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='DEFAULT VALUE', max_length=50)),
                ('descripcion', models.CharField(default='DEFAULT VALUE', max_length=500)),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'categorias',
            },
        ),
    ]
